namespace MiniPL
{
    public enum Symbol
    {
        EndOfInput,
        Identifier,
        Variable,
        IntegerLiteral,
        Colon,
        Assigment,
        Addition,
        Multiplication,
        ClosureOpen,
        ClosureClose,
        SemiColon,
        IntegerType,
        PrintProcedure,
        StringLiteral,
        ReadProcedure,
        For,
        In,
        Range,
        Substraction,
        Equality,
        End,
        Assert,
        StringType,
        BooleanType,
        Do,
        Division,
        LogicalAnd,
        LogicalNot,
        LessThan
    }
}
